namespace InfiniteForgeConstants.Forge_UI.Object_Browser.Folders.Accents;

public class DestructiblesMPFolder : ForgeUIFolder
{
    public DestructiblesMPFolder() : base("Destructibles_MP")
    {
        AddItem("Cafe Stool MP");
        AddItem("Cardboard Box A Bluetape MP");
        AddItem("Cardboard Box A MP");
        AddItem("Cardboard Box A White MP");
        AddItem("Cardboard Box B Bluetape MP");
        AddItem("Cardboard Box B MP");
        AddItem("Cardboard Box B MP");
        AddItem("Cardboard Box C MP");
        AddItem("Cardboard Box C MP");
        AddItem("Cardboard Box Open MP");
        AddItem("Clay Pot A MP");
        AddItem("Clay Pot B MP");
        AddItem("Clay Pot C MP");
        AddItem("Clay Pot C w/ Palm Tree A MP");
        AddItem("Clay Pot C w/ Palm Tree B MP");
        AddItem("Clay Pot C w/ Palm Tree C MP");
        AddItem("Conduit Computer MP");
        AddItem("Destructible Keypad B - Closed MP");
        AddItem("Destructible Keypad B MP");
        AddItem("Destructible Monitor A MP");
        AddItem("Destructible Monitor C MP");
        AddItem("Destructible Monitor D MP");
        AddItem("Destructible potted plant A MP");
        AddItem("Destructible potted plant B MP");
        AddItem("Electrical Box A MP");
        AddItem("Electrical Box B MP");
        AddItem("Electrical Box C MP");
        AddItem("Electrical Box E MP");
        AddItem("Electrical Box F MP");
        AddItem("Electrical Box G MP");
        AddItem("Fire Extinguisher MP");
        AddItem("Framed Picture A MP");
        AddItem("Framed Picture B MP");
        AddItem("Framed Picture C MP");
        AddItem("Framed Picture D MP");
        AddItem("Market Table A Fruits A MP");
        AddItem("Market Table A Fruits B MP");
        AddItem("Market Table A Fruits C MP");
        AddItem("Market Table A Fruits D MP");
        AddItem("Market Table A Fruits E MP");
        AddItem("Oxygen Tank MP");
        AddItem("Plastic Crate Empty MP");
        AddItem("Small wooden backless bench MP");
        AddItem("Soda Crate Empty MP");
        AddItem("Soda Crate w/Soda MP");
        AddItem("Stack of books B MP");
        AddItem("Target Dummy Brute MP");
        AddItem("Target Dummy Grunt MP");
        AddItem("Wet Floor MP");
        AddItem("Wood Chair A MP");
        AddItem("Wood Plank Pile MP");
        AddItem("Wooden Bench MP");
        AddItem("Wooden Box Apple MP");
        AddItem("Wooden Box Banana MP");
        AddItem("Wooden Box Carrot MP");
        AddItem("Wooden Box Empty MP");
        AddItem("Wooden Box Mango MP");
        AddItem("Wooden Box Tomato MP");
        AddItem("Wooden Box Watermelon MP");
        AddItem("Wooden Column Square Broken Railing A MP");
        AddItem("Wooden Column Square Broken Railing B MP");
        AddItem("Wooden Column Square MP");
        AddItem("Wooden Crate A MP");
        AddItem("Wooden Crate B MP");
        AddItem("Wooden Crate C MP");
        AddItem("Wooden Lattice MP");
        AddItem("Wooden Market Table MP");
        AddItem("Wooden Pallet A MP");
        AddItem("Wooden Pallet B MP");
        AddItem("Wooden Pallet C MP");
        AddItem("Wooden Railing Broken A MP");
        AddItem("Wooden Railing Broken B MP");
        AddItem("Wooden Railing MP");
        AddItem("Wooden Railing Stairs MP");
        AddItem("Wooden Table MP");
        AddItem("Woven Basket MP");
    }
}