namespace InfiniteForgeConstants.Forge_UI.Object_Browser.Folders.Accents;

public class ForerunnerFolder : ForgeUIFolder
{
    public ForerunnerFolder() : base("Forerunner")
    {
        AddItem("Forerunner 24 x 60 x 24 Angled Support");
        AddItem("Forerunner 8 x 36 x 32 Angled Support");
        AddItem("Forerunner Angled Cover/Support");
        AddItem("Forerunner Beam A");
        AddItem("Forerunner Beam B");
        AddItem("Forerunner Behemoth Door");
        AddItem("Forerunner Behemoth Hatch w/Material Swa");
        AddItem("Forerunner Catwalk A");
        AddItem("Forerunner Catwalk B");
        AddItem("Forerunner Catwalk Beam");
        AddItem("Forerunner Catwalk C");
        AddItem("Forerunner Catwalk D");
        AddItem("Forerunner Catwalk E");
        AddItem("Forerunner Catwalk Railing");
        AddItem("Forerunner Control Point");
        AddItem("Forerunner Cover Block");
        AddItem("Forerunner Cover Full A");
        AddItem("Forerunner Cover Full B");
        AddItem("Forerunner Cover Full C");
        AddItem("Forerunner Cover Full D");
        AddItem("Forerunner Cover Half A");
        AddItem("Forerunner Cover Half B");
        AddItem("Forerunner Decorative Pylon");
        AddItem("Forerunner Door Small");
        AddItem("Forerunner Door Small Animated");
        AddItem("Forerunner Hex Pillar 128 x 384");
        AddItem("Forerunner Hex Pillar 16 x 08");
        AddItem("Forerunner Hex Pillar 16 x 24");
        AddItem("Forerunner Hex Pillar 16 x 384");
        AddItem("Forerunner Hex Pillar 16 x 48");
        AddItem("Forerunner Hex Pillar 32 x 96");
        AddItem("Forerunner Hex Pillar 64 x 120");
        AddItem("Forerunner Hex Pillar 64 x 168 A");
        AddItem("Forerunner Hex Pillar 64 x 168 B");
        AddItem("Forerunner Hex Pillar 64 x 168 C");
        AddItem("Forerunner Hex Pillar 64 x 168 D");
        AddItem("Forerunner Hex Pillar 64 x 168 E");
        AddItem("Forerunner Hex Pillar 64 x 168 F");
        AddItem("Forerunner Hex Pillar 64 x 168 G");
        AddItem("Forerunner Hex Pillar 64 x 168 H");
        AddItem("Forerunner Hex Pillar 64 x 168 I");
        AddItem("Forerunner Hex Pillar 64 x 168 J");
        AddItem("Forerunner Hex Pillar 64 x 168 K");
        AddItem("Forerunner Hub Cover");
        AddItem("Forerunner Light Bridge Emitter");
        AddItem("Forerunner Machinery Cover A");
        AddItem("Forerunner Machinery Cover B");
        AddItem("Forerunner Pedestal");
        AddItem("Forerunner Pillar A");
        AddItem("Forerunner Pillar B");
        AddItem("Forerunner Pillar C");
        AddItem("Forerunner Piston");
        AddItem("Forerunner Platform 06 x 10 x 44");
        AddItem("Forerunner Platform 10 x 06 x 48");
        AddItem("Forerunner Platform 12 x 04 x 56");
        AddItem("Forerunner Platform 12 x 10 x 42 A");
        AddItem("Forerunner Platform 12 x 10 x 42 B");
        AddItem("Forerunner Platform 16 x 08 x 42");
        AddItem("Forerunner Platform 18 x 06 x 46 A");
        AddItem("Forerunner Platform 18 x 06 x 46 B");
        AddItem("Forerunner Plinth");
        AddItem("Forerunner Podium Large A");
        AddItem("Forerunner Podium Large B");
        AddItem("Forerunner Ramp");
        AddItem("Forerunner Ramp Cover");
        AddItem("Forerunner Support A");
        AddItem("Forerunner Support B");
        AddItem("Forerunner Support C");
        AddItem("Forerunner Support D");
        AddItem("Forerunner Totem Ring A");
        AddItem("Forerunner Totem Ring B");
        AddItem("Forerunner Totem Ring C");
        AddItem("Forerunner Totem Ring Chunk");
        AddItem("Forerunner Totem Ring Debris");
    }
}