namespace InfiniteForgeConstants.Forge_UI.Object_Browser.Folders.Accents;

public class UNSCFolder : ForgeUIFolder
{
    public UNSCFolder() : base("UNSC")
    {
        AddItem("Angled Wall Insert");
        AddItem("Angled Wire Fence");
        AddItem("Bridge Support Pillar");
        AddItem("Bulkhead");
        AddItem("Bullet Pile Large");
        AddItem("Bullet Pile Small");
        AddItem("Canvas Bag");
        AddItem("Ceiling Conduit");
        AddItem("Ceiling Corner Deco");
        AddItem("Chute Hatch");
        AddItem("Clip-on Light A");
        AddItem("Clip-on Light B");
        AddItem("Clip-on Light Clamp");
        AddItem("Concrete Block A");
        AddItem("Concrete Block B");
        AddItem("Concrete Block C");
        AddItem("Concrete Block D");
        AddItem("Concrete Block E");
        AddItem("Concrete Block F");
        AddItem("Concrete Column");
        AddItem("Conduit Cover");
        AddItem("Control Panel A");
        AddItem("Cooling Fin");
        AddItem("Crumpled Vent Panel");
        AddItem("Data Tower");
        AddItem("Dry Erase Board");
        AddItem("Dry Erase Marker");
        AddItem("Electrical Junction Boxes");
        AddItem("Finned Accent");
        AddItem("Floor Machine");
        AddItem("Floor Podium");
        AddItem("Floor Storage");
        AddItem("Floor Tower");
        AddItem("Folding Chair");
        AddItem("Gantry Crane");
        AddItem("Generator Medium");
        AddItem("Generator Small");
        AddItem("Generator Standalone");
        AddItem("Gun Mount Flap A");
        AddItem("Gun Mount Flap B");
        AddItem("Gun Mount Girder A");
        AddItem("Gun Mount Panel A");
        AddItem("Gun Mount Support Girder A");
        AddItem("Hanging UNSC Monitor");
        AddItem("Jumbotron Monitors");
        AddItem("Large UNSC Pillar");
        AddItem("Large Wall Module");
        AddItem("Machine Large");
        AddItem("Metal Beam");
        AddItem("Metal Shutter");
        AddItem("Mounted Speaker");
        AddItem("Overhead Track");
        AddItem("Pallet Hydrogen Bottles");
        AddItem("Pallet Water Barrels");
        AddItem("Panel Cover");
        AddItem("Patch Kit");
        AddItem("Radio Reciever");
        AddItem("Rectangle Cover");
        AddItem("Rolling Chair");
        AddItem("Roof Exhaust");
        AddItem("Roof Hatch Vent");
        AddItem("Rooftop A");
        AddItem("Round Platform");
        AddItem("Sleeping Bag Packed");
        AddItem("Sleeping Bag Unrolled");
        AddItem("Target - Small");
        AddItem("Trim Beam A");
        AddItem("Trim Beam B");
        AddItem("Trim Beam Corner");
        AddItem("Truss/Girder");
        AddItem("UNSC Bot Separation Pen");
        AddItem("UNSC Catwalk Long");
        AddItem("UNSC Catwalk Short");
        AddItem("UNSC Crane Body A");
        AddItem("UNSC Crane Hook A");
        AddItem("UNSC Crane Top A");
        AddItem("UNSC Crane Trolley A");
        AddItem("UNSC Duffle Bag");
        AddItem("UNSC Generator");
        AddItem("UNSC Powercore");
        AddItem("UNSC Road");
        AddItem("UNSC Roof Panel Shield");
        AddItem("UNSC Wall Tech Extra Large A");
        AddItem("UNSC Wall Tech Extra Large B");
        AddItem("UNSC Wall Tech Extra Large C");
        AddItem("UNSC Wall Tech Extra Large D");
        AddItem("UNSC Wall Tech Large A");
        AddItem("UNSC Wall Tech Large C");
        AddItem("UNSC Wall Tech Med A");
        AddItem("UNSC Wall Tech Med B");
        AddItem("UNSC Wall Tech Med C");
        AddItem("UNSC Wall Tech Med D");
        AddItem("UNSC Wall Tech Med E");
        AddItem("UNSC Wall Tech Small A");
        AddItem("UNSC Wall Trim Straight A");
        AddItem("Wall Keypad");
        AddItem("Wall Meter");
        AddItem("Wall Module");
        AddItem("Wreckage Hull Box A");
        AddItem("Wreckage Hull Panel A");
        AddItem("Wreckage Hull Panel A Large");
        AddItem("Wreckage Hull Panel B Large");
        AddItem("Wreckage Hull Support Beam B");
        AddItem("Wreckage Panel");
        AddItem("Wreckage Panel A");
        AddItem("Wreckage Panel B");
        AddItem("Wreckage Panel C");
        AddItem("Wreckage Panel D");
    }
}