namespace InfiniteForgeConstants.NodeGraphSettings;

public enum WeaponCombinationConfigurationTypes
{
    BR75_BREACHER = 0,
    BACKDRAFT_CINDERSHOT = 1,
    CONVERGENCE_BULLDOG = 2,
    CALCINE_DISRUPTOR = 3,
    DUELIST_ENERGY_SWORD = 4,
    ELITE_BLOODBLADE = 5,
    RUSHDOWN_HAMMER = 6,
    DIMINISHER_OF_HOPE = 7,
    SCATTERBOUND_HEATWAVE = 8,
    M41_TRACKER = 9,
    MA40_LONGSHOT = 10,
    NONE = 11,
    RIVEN_MANGLER = 12,
    STRIKER_SIDEKICK = 13,
    PURSUIT_HYDRA = 14,
    PINPOINT_NEEDLER = 15,
    UNBOUND_PLASMA_PISTOL = 16,
    RAPIDFIRE_PULSE_CARBINE = 17,
    RAVAGER_REBOUND = 18,
    S7_FLEXFIRE_SNIPER = 19,
    ARCANE_SENTINEL_BEAM = 20,
    PURGING_SHOCK_RIFLE = 21,
    VOLATILE_SKEWER = 22,
    STALKER_RIFLE_ULTRA = 23,
    IMPACT_COMMANDO = 24
}